sudo: false
language: node_js
node_js:
  - "7"

before_install:
  - git config --global user.name "liujian10"
  - git config --global user.email "mapleliu1@gmail.com"

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build
  - cd dist
  - git init
  - git add -A
    - git commit -m "Deploy mapleliu"
    - git push -u https://$ML_TOKEN@github.com/liujian10liujian10/liujian10.github.io.git HEAD:master --force
